name: Build & Deploy

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Setting up Github Actions...
        uses: actions/checkout@v3

      - name: Setting up Node environment...
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Building React app...
        run: |
          npm ci
          npm run build --if-present

      - name: Packaging build to a tarball...
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            captain-definition
            build/
          outPath: deploy.tar

      - name: Deploying app to CapRover...
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
